{{- if and (.Values.brupop) (.Values.brupop.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bottlerocket-update-operator
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: addons/brupop
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        brupop:
        {{- toYaml .Values.brupop | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: brupop-bottlerocket-aws
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end -}}