{{- if and (.Values.crossplane) (.Values.crossplane.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: addons/crossplane
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        crossplane:
          configuration:
            packages:
              - xpkg.upbound.io/upbound/provider-aws-s3:v0.40.0
              - xpkg.upbound.io/upbound/provider-vault:v0.2.0
        {{- toYaml .Values.crossplane | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace={{ .Values.crossplane.createNamespace | default "true" }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}